### PR TITLE
feat: 🎸 export TypeScript types and improve build process

### PR DESCRIPTION
**Pull request by streamich**
- Export TypeScript types
- Build with `tsc`
- Remove Gulp
- Publish to NPM only `lib/` folder
- Upgrade TypeScript to latest version
- Import React as wildcard
- Refresh readme links

### CODE REVIEW

**Comment by tomByrer** [comment]
I suggest not making`yarn` mandatory; not everyone will or can have it installed.  Works crappy on my Windows machine, crashes on build on my Linux install.  & others find issues with Yarn:

https://iamturns.com/yarn-vs-npm-2018/

**Comment by streamich** [comment]
@tomByrer do you mean not to include `yarn.lock` or not including `yarn build` etc.. commands?

**Comment by streamich** [comment]
Build version: __`2.1.0-pr-13.88`__ :crossed_fingers: [`fix-build`](https://github.com/streamich/libreact/tree/fix-build) on [*Travis*](https://travis-ci.org/streamich/libreact/builds/86783705) :tada:

**Comment by streamich** [comment]
Build version: __`2.1.0-pr-13.90`__ :crossed_fingers: [`fix-build`](https://github.com/streamich/libreact/tree/fix-build) on [*Travis*](https://travis-ci.org/streamich/libreact/builds/86785246) :tada:

**Comment by streamich** [comment]
Build version: __`2.1.0-pr-13.92`__ :crossed_fingers: [`fix-build`](https://github.com/streamich/libreact/tree/fix-build) on [*Travis*](https://travis-ci.org/streamich/libreact/builds/86787553) :tada:

**Comment by streamich** [comment]
Build version: __`2.1.0-pr-13.94`__ :crossed_fingers: [`fix-build`](https://github.com/streamich/libreact/tree/fix-build) on [*Travis*](https://travis-ci.org/streamich/libreact/builds/86788342) :tada:

**Comment by streamich** [comment]
Build version: __`2.1.0-pr-13.96`__ :crossed_fingers: [`fix-build`](https://github.com/streamich/libreact/tree/fix-build) on [*Travis*](https://travis-ci.org/streamich/libreact/builds/86791380) :tada:

**Comment by streamich** [comment]
Build version: __`2.1.0-pr-13.98`__ :crossed_fingers: [`fix-build`](https://github.com/streamich/libreact/tree/fix-build) on [*Travis*](https://travis-ci.org/streamich/libreact/builds/86792746) :tada:

**Pull request merged**
